[package]
name = "fallout-classic-rewritten"
resolver = "3"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
package.version = "0.1.0"
package.edition = "2024"

members = [
    "deps/common",
    "deps/acm",
    "deps/mve",
    "deps/dat",
    "deps/pal",
    "deps/frm",
    "deps/av",

    "tools/read-dat",
    "tools/read-file",
    "tools/browser",
]

[features]
tools = []

[[bin]]
name = "fallout-classic-rewritten"
path = "src/main.rs"

[dependencies]
acm = { path = "./deps/acm" }
mve = { path = "./deps/mve" }

[profile.release-with-debug]
inherits = "release"
debug = true
