[package]
name = "dat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
flate2 = "1.0.24"
libc = "0.2.132"
