[package]
name = "mve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
itertools = "0.10.5"
nom = "7.1.3"
tailcall = "0.1.6"
